apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging

spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: rest
    - protocol: TCP
      port: 9300
      targetPort: 9300
      name: inter-node
