apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
  namespace: logging
spec:
  storageClassName: minikube
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /mnt/elasticsearch/data

